<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#shuffling" data-toc-modified-id="shuffling-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>shuffling</a></span></li><li><span><a href="#separazione-di-train-e-test" data-toc-modified-id="separazione-di-train-e-test-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>separazione di train e test</a></span></li><li><span><a href="#implementazione-KNN" data-toc-modified-id="implementazione-KNN-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>implementazione KNN</a></span></li></ul></div>

In [1]:
from sklearn import datasets

In [2]:
data = datasets.load_wine()
print(data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])


In [3]:
#estrarre la matrice delle feature e il vettore delle etichette
X = data['data']
y = data['target']
print(X.shape,y.shape)

(178, 13) (178,)


In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

##  shuffling

In [5]:
import numpy as np
from numpy.random import default_rng

In [6]:
rnd = default_rng(seed=42)

In [7]:
permutazione = np.arange(0,150)
rnd.shuffle(permutazione)
permutazione

array([ 70,  79, 134,   3, 123, 120,  81, 105, 130,  33, 124,   4,  24,
       111, 129,  25,   2,  20, 125,  85,  37, 143, 126,  91,   0,  87,
        78,  27,  82,  90,  94,  56,  96, 103,  52,  13, 114,  28, 131,
         5,  66, 116, 106, 135,  12,  89,  54,  68, 122,  46,  50, 101,
       144,  45,  86,  73,   7,  18,  51, 146,  72,  92,  38,   8, 100,
        98,  21,  71,  59,  65, 132, 108,  93,  26,  75, 133, 139,  74,
        10,  88,  29,  63,  55,  95,  42,  17,  39, 149,  53,  76, 107,
        40,  80,  69, 118,   1, 148, 104, 119,  11, 145,  84,  83,  43,
       128,  32,  61,  57, 115,  23, 147, 121,  15,  48,  60, 109,   9,
        62,  31, 127, 117,  16,  44, 112, 138,  99, 142,  67,  34,  30,
        58,  35,  77,  49,   6, 102, 137,  41, 110,  22,  19,  64,  47,
       113, 140,  14, 141,  36,  97, 136])

In [8]:
X = X[permutazione]
y = y[permutazione]

## separazione di train e test

In [9]:
"""
train-test set
80-20
"""

'\ntrain-test set\n80-20\n'

In [10]:
n_train = int(X.shape[0]*0.8)
#n_test = X.shape[0] - n_train
X_train, y_train = X[0:n_train], y[0:n_train]
X_test, y_test = X[n_train:], y[n_train:]

In [11]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((120, 13), (120,), (30, 13), (30,))

## implementazione KNN

In [12]:
def knn_predict_single(x_new, k, X_train, y_train):
    distanze = []
    for x_tr_i in X_train:
        d = np.sqrt(np.sum((x_new-x_tr_i)**2))
        distanze.append(d)
    distanze = np.array(distanze)
    k_neighbors = np.argsort(distanze)[:k]
    occorrenze = np.bincount(y_train[k_neighbors], minlength=3)
    y_new_pred = np.argmax(occorrenze)
    return y_new_pred

In [13]:
def knn_predict(X_new, k, X_train, y_train):
    y_pred_test = []
    for x_test_i in X_new:
        y_pred_test_i = knn_predict_single(x_test_i,k,X_train, y_train)
        y_pred_test +=[y_pred_test_i]
        
    return np.array(y_pred_test)

In [14]:
y_pred_test = knn_predict(X_test,13, X_train, y_train)
y_pred_test

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1])

In [15]:
y_pred_test

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1])

In [16]:
y_test

array([1, 0, 0, 1, 2, 1, 2, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 1,
       0, 1, 2, 0, 2, 0, 1, 2])

In [17]:
y_pred_test.shape, y_test.shape

((30,), (30,))

In [18]:
y_pred_test == y_test

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False])

In [19]:
#contare quanti true e quante false
np.bincount(y_pred_test == y_test)

array([ 6, 24])

In [20]:
np.sum(y_pred_test == y_test)

24

In [21]:
#nella prossima lezione
#valutazione dei risultati
#visualizzare i risultati - l'andamento di k rispetto al valore dell'accuratezza